
import java.awt.Toolkit;

import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class customerPage extends javax.swing.JFrame {

        //mouse drag
        int mouseX;
        int mouseY;
        // screen pos
        int wid = (Toolkit.getDefaultToolkit().getScreenSize().width)/2-533;
        int hit = (Toolkit.getDefaultToolkit().getScreenSize().height)/2-400;

        int X;
        int Y;
        String customer_id = "";
        
    public customerPage(int x, int y, String customerID) {
        initComponents();
        
        
        //icon image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
        // position
        this.setLocation(x,y);
        
        System.out.println(customerID);
        customer_id=customerID;
        
    }
    
    public customerPage() {
        initComponents();
        
        //icon image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
        // position
        this.setLocation(wid,hit);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hospitalList_1 = new javax.swing.JLabel();
        hospitalList_ = new javax.swing.JLabel();
        adressSelect = new javax.swing.JComboBox<>();
        hospitalSelect = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        reqVaccine_ = new javax.swing.JLabel();
        track_ = new javax.swing.JLabel();
        appointment_ = new javax.swing.JLabel();
        payemnt_ = new javax.swing.JLabel();
        effects_ = new javax.swing.JLabel();
        slip_ = new javax.swing.JLabel();
        logout_ = new javax.swing.JLabel();
        report_ = new javax.swing.JLabel();
        getApp_ = new javax.swing.JLabel();
        drag_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hospitalList_1.setText("Select the hospital you prefer*");
        getContentPane().add(hospitalList_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 250, 20));

        hospitalList_.setText("Select the hospital area you prefer*");
        getContentPane().add(hospitalList_, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 270, 20));

        adressSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Comilla", "Rajshahi", "Sylhet", "Barisal", "Chittagong", "Khulna", "Mymensingh", "Rangpur" }));
        adressSelect.setBorder(null);
        adressSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressSelectActionPerformed(evt);
            }
        });
        getContentPane().add(adressSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 270, 40));

        hospitalSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalSelectActionPerformed(evt);
            }
        });
        getContentPane().add(hospitalSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 270, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reqbutton.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 475, 102, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listbutton.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 365, 102, 30));

        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 28, 37, 37));

        reqVaccine_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/request vaccine hover.png"))); // NOI18N
        reqVaccine_.setText("jLabel2");
        reqVaccine_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reqVaccine_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reqVaccine_MouseMoved(evt);
            }
        });
        reqVaccine_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reqVaccine_MouseClicked(evt);
            }
        });
        getContentPane().add(reqVaccine_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 195, 60));

        track_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/track req.png"))); // NOI18N
        track_.setText("jLabel2");
        track_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        track_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                track_MouseMoved(evt);
            }
        });
        track_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                track_MouseClicked(evt);
            }
        });
        getContentPane().add(track_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, 195, 60));

        appointment_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appointment.png"))); // NOI18N
        appointment_.setText("jLabel2");
        appointment_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appointment_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                appointment_MouseMoved(evt);
            }
        });
        appointment_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointment_MouseClicked(evt);
            }
        });
        getContentPane().add(appointment_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, 195, 60));

        payemnt_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment.png"))); // NOI18N
        payemnt_.setText("jLabel2");
        payemnt_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payemnt_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                payemnt_MouseMoved(evt);
            }
        });
        payemnt_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payemnt_MouseClicked(evt);
            }
        });
        getContentPane().add(payemnt_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 263, 195, 60));

        effects_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sideeffects.png"))); // NOI18N
        effects_.setText("jLabel2");
        effects_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        effects_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                effects_MouseMoved(evt);
            }
        });
        effects_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                effects_MouseClicked(evt);
            }
        });
        getContentPane().add(effects_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 323, 195, 60));

        slip_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slip gen.png"))); // NOI18N
        slip_.setText("jLabel2");
        slip_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slip_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                slip_MouseMoved(evt);
            }
        });
        slip_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slip_MouseClicked(evt);
            }
        });
        getContentPane().add(slip_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 383, 195, 60));

        logout_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logout_.setText("jLabel2");
        logout_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logout_MouseMoved(evt);
            }
        });
        logout_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_MouseClicked(evt);
            }
        });
        getContentPane().add(logout_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 609, 195, 60));

        report_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        report_.setText("jLabel2");
        report_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        report_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                report_MouseMoved(evt);
            }
        });
        report_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                report_MouseClicked(evt);
            }
        });
        getContentPane().add(report_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 669, 195, 60));

        getApp_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.png"))); // NOI18N
        getApp_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getApp_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                getApp_MouseMoved(evt);
            }
        });
        getApp_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getApp_MouseClicked(evt);
            }
        });
        getContentPane().add(getApp_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 729, 195, 60));

        drag_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main panel.png"))); // NOI18N
        drag_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drag_MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drag_MouseMoved(evt);
            }
        });
        drag_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drag_MousePressed(evt);
            }
        });
        getContentPane().add(drag_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1066, 799));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adressSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressSelectActionPerformed

    private void reqVaccine_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reqVaccine_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccine hover.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_reqVaccine_MouseMoved

    private void reqVaccine_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reqVaccine_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reqVaccine_MouseClicked

    private void track_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_track_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccine hover.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req hover.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_track_MouseMoved

    private void track_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_track_MouseClicked
        // TODO add your handling code here:
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();
        
        customerTrackReq ctr = new customerTrackReq(nx,ny,customer_id);
        ctr.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_track_MouseClicked

    private void appointment_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointment_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccine hover.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointmenthover.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_appointment_MouseMoved

    private void appointment_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointment_MouseClicked
        // TODO add your handling code here:
        
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();
        
        customerAppointment ca = new customerAppointment(nx,ny,customer_id);
        ca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appointment_MouseClicked

    private void payemnt_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payemnt_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccine hover.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment hover.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_payemnt_MouseMoved

    private void payemnt_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payemnt_MouseClicked
        // TODO add your handling code here:
        
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();
        
        customerPayment cp = new customerPayment(nx,ny,customer_id);
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_payemnt_MouseClicked

    private void effects_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_effects_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccine hover.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects hover.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_effects_MouseMoved

    private void effects_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_effects_MouseClicked
        // TODO add your handling code here:
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();
        
        customerSideEffects cse = new customerSideEffects(nx,ny,customer_id);
        cse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_effects_MouseClicked

    private void slip_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slip_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccine hover.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen hover.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_slip_MouseMoved

    private void slip_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slip_MouseClicked
        // TODO add your handling code here:
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();

        slip slip = new slip(nx,ny,customer_id);
        slip.setVisible(true);
    }//GEN-LAST:event_slip_MouseClicked

    private void logout_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_MouseMoved
        // TODO add your handling code here:
        ImageIcon logout = new ImageIcon(getClass().getResource("logoutHOver.png"));
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("report.png"));
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("app.png"));
        getApp_.setIcon(gapp);
    }//GEN-LAST:event_logout_MouseMoved

    private void logout_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_MouseClicked
        // TODO add your handling code here:
        this.dispose();
        accessibility ac = new accessibility();
        ac.setVisible(true);
    }//GEN-LAST:event_logout_MouseClicked

    private void report_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_MouseMoved
        // TODO add your handling code here:
        ImageIcon logout = new ImageIcon(getClass().getResource("logout.png"));
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("reportHover.png"));
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("app.png"));
        getApp_.setIcon(gapp);
    }//GEN-LAST:event_report_MouseMoved

    private void report_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_report_MouseClicked

    private void getApp_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getApp_MouseMoved
        // TODO add your handling code here:
        ImageIcon logout = new ImageIcon(getClass().getResource("logout.png"));
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("report.png"));
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("appHover.png"));
        getApp_.setIcon(gapp);
    }//GEN-LAST:event_getApp_MouseMoved

    private void getApp_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getApp_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_getApp_MouseClicked

    private void drag_MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_drag_MouseDragged

    private void drag_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccine hover.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);

        ImageIcon logout = new ImageIcon(getClass().getResource("logout.png"));
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("report.png"));
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("app.png"));
        getApp_.setIcon(gapp);
    }//GEN-LAST:event_drag_MouseMoved

    private void drag_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_drag_MousePressed

    private void hospitalSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalSelectActionPerformed

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();

        customerProfile cp = new customerProfile (nx,ny,customer_id);
        cp.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_profileMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        try {
            
        
            hospitalSelect.removeAllItems();    
              String address;
            address=adressSelect.getSelectedItem().toString();

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
            "jdbc:sqlserver://localhost:1433;databaseName=SD3104;selectMethod=cursor", "sa", "123456");

            Statement statement = connection.createStatement();
            ResultSet resultSet = statement
            .executeQuery("SELECT hospital_name FROM hospital where hospital_adress='"+address+"'");


            while(resultSet.next()){

                String hospitalname=resultSet.getString("hospital_name");
                hospitalSelect.addItem(hospitalname);

            }

 
        } catch (Exception e) {
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
        
        try {
            
               
                String hospital_name;
                String hospital_adress;
                String order_id="CDVO";
                
                
                
                
 
            
       
                
                
                
                
                
                
                
                
                
                
                
                
                
                
          
          
        hospital_name=hospitalSelect.getSelectedItem().toString();
        hospital_adress=adressSelect.getSelectedItem().toString();
        
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
Connection connection = DriverManager
.getConnection(
"jdbc:sqlserver://localhost:1433;databaseName=SD3104;selectMethod=cursor", "sa", "123456");

Statement statement = connection.createStatement();
ResultSet resultSet = statement
.executeQuery("SELECT hospital_id FROM hospital where hospital_name='"+hospital_name+"' and hospital_adress='"+hospital_adress+"'");


   resultSet.next();
            
            String hospital_id=resultSet.getString("hospital_id");
            
            
            
            
            
          
            //generate id
            String oid = "SELECT COUNT(*) AS ordercount FROM orders";
            PreparedStatement pstid =  connection.prepareStatement (oid);
            ResultSet rsid = pstid.executeQuery();
            int idpre=0;
            
            if (rsid.next()){
            idpre = rsid.getInt("ordercount");
            }
            idpre+=1;
            String idpr = Integer.toString(idpre);
            order_id = order_id+idpr;           
            
            
            
            
            
            
            
            
resultSet = statement
.executeQuery("insert into orders values('"+order_id+"','"+customer_id+"','"+hospital_id+"')"  );    
        

 
} catch (Exception e) {
e.printStackTrace();
}
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adressSelect;
    private javax.swing.JLabel appointment_;
    private javax.swing.JLabel drag_;
    private javax.swing.JLabel effects_;
    private javax.swing.JLabel getApp_;
    private javax.swing.JLabel hospitalList_;
    private javax.swing.JLabel hospitalList_1;
    private javax.swing.JComboBox<String> hospitalSelect;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logout_;
    private javax.swing.JLabel payemnt_;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel report_;
    private javax.swing.JLabel reqVaccine_;
    private javax.swing.JLabel slip_;
    private javax.swing.JLabel track_;
    // End of variables declaration//GEN-END:variables
}
