
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class customerTrackReq extends javax.swing.JFrame {

    //mouse drag
        int mouseX;
        int mouseY;
        // screen pos
        int wid = (Toolkit.getDefaultToolkit().getScreenSize().width)/2-533;
        int hit = (Toolkit.getDefaultToolkit().getScreenSize().height)/2-400;

        int X;
        int Y;
        String customer_id="";
        
       
        
    public customerTrackReq(int x, int y, String customerID) {
        initComponents();
        
         //icon image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
        // position
        this.setLocation(x,y);
        
        System.out.println(customerID);
        customer_id=customerID;
        
        ImageIcon s0 = new ImageIcon(getClass().getResource("paid.png"));
        state1_.setIcon(s0);
        acc_.setText("Account created");
        
        
        try {
                                          
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
Connection connection = DriverManager
.getConnection(
"jdbc:sqlserver://localhost:1433;databaseName=SD3104;selectMethod=cursor", "sa", "123456");
System.out.println("DATABASE NAME IS:"
+ connection.getMetaData().getDatabaseProductName());
Statement statement = connection.createStatement();

ResultSet resultSet=statement.executeQuery("select hospital_name from accounts inner join hospital on hospital.hospital_id=accounts.hospital_id where customer_id='"+customer_id+"'");

            

if(resultSet.next()){
    
    hospital_name.setText(resultSet.getString("hospital_name"));
    status.setText("Approved");
    ImageIcon s1 = new ImageIcon(getClass().getResource("paid.png"));
        state1_.setIcon(s1);
        
    ImageIcon s2 = new ImageIcon(getClass().getResource("pending.png"));
        state2_.setIcon(s2);
        
    ImageIcon s3 = new ImageIcon(getClass().getResource("request.png"));
        state3_.setIcon(s3);    
    
    completed_.setText("Done");    
    
}

ResultSet rst=statement.executeQuery("select hospital_name from orders inner join hospital on hospital.hospital_id=orders.hospital_id where customer_id='"+customer_id+"'");
 



if(rst.next()){
         
   hospital_name.setText(rst.getString("hospital_name"));
   status.setText("Pending");
   ImageIcon s1 = new ImageIcon(getClass().getResource("paid.png"));
        state1_.setIcon(s1);
        
   ImageIcon s2 = new ImageIcon(getClass().getResource("pending.png"));
        state2_.setIcon(s2);
        
        jLabel1.setText("Request for Covid-19 vaccine at ");
    
}



} catch (Exception e) {
e.printStackTrace();
}
        
        
        
        
    }
    
    public customerTrackReq() {
        initComponents();
        
        //icon image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
        // position
        this.setLocation(wid,hit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reqVaccine_ = new javax.swing.JLabel();
        track_ = new javax.swing.JLabel();
        appointment_ = new javax.swing.JLabel();
        payemnt_ = new javax.swing.JLabel();
        effects_ = new javax.swing.JLabel();
        slip_ = new javax.swing.JLabel();
        logout_ = new javax.swing.JLabel();
        report_ = new javax.swing.JLabel();
        getApp_ = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        completed_ = new javax.swing.JLabel();
        acc_ = new javax.swing.JLabel();
        hospital_name = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        state1_ = new javax.swing.JLabel();
        state2_ = new javax.swing.JLabel();
        state3_ = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        drag_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reqVaccine_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/request vaccing.png"))); // NOI18N
        reqVaccine_.setText("jLabel2");
        reqVaccine_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reqVaccine_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reqVaccine_MouseMoved(evt);
            }
        });
        reqVaccine_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reqVaccine_MouseClicked(evt);
            }
        });
        getContentPane().add(reqVaccine_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 195, 60));

        track_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/track req hover.png"))); // NOI18N
        track_.setText("jLabel2");
        track_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        track_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                track_MouseMoved(evt);
            }
        });
        track_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                track_MouseClicked(evt);
            }
        });
        getContentPane().add(track_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, 195, 60));

        appointment_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appointment.png"))); // NOI18N
        appointment_.setText("jLabel2");
        appointment_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appointment_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                appointment_MouseMoved(evt);
            }
        });
        appointment_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointment_MouseClicked(evt);
            }
        });
        getContentPane().add(appointment_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, 195, 60));

        payemnt_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment.png"))); // NOI18N
        payemnt_.setText("jLabel2");
        payemnt_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payemnt_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                payemnt_MouseMoved(evt);
            }
        });
        payemnt_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payemnt_MouseClicked(evt);
            }
        });
        getContentPane().add(payemnt_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 263, 195, 60));

        effects_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sideeffects.png"))); // NOI18N
        effects_.setText("jLabel2");
        effects_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        effects_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                effects_MouseMoved(evt);
            }
        });
        effects_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                effects_MouseClicked(evt);
            }
        });
        getContentPane().add(effects_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 323, 195, 60));

        slip_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slip gen.png"))); // NOI18N
        slip_.setText("jLabel2");
        slip_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slip_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                slip_MouseMoved(evt);
            }
        });
        slip_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slip_MouseClicked(evt);
            }
        });
        getContentPane().add(slip_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 383, 195, 60));

        logout_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logout_.setText("jLabel2");
        logout_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logout_MouseMoved(evt);
            }
        });
        logout_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_MouseClicked(evt);
            }
        });
        getContentPane().add(logout_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 609, 195, 60));

        report_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        report_.setText("jLabel2");
        report_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        report_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                report_MouseMoved(evt);
            }
        });
        report_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                report_MouseClicked(evt);
            }
        });
        getContentPane().add(report_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 669, 195, 60));

        getApp_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.png"))); // NOI18N
        getApp_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getApp_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                getApp_MouseMoved(evt);
            }
        });
        getApp_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getApp_MouseClicked(evt);
            }
        });
        getContentPane().add(getApp_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 729, 195, 60));

        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 28, 37, 37));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 280, 282, 41));

        completed_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completed_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(completed_, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 280, 160, 41));

        acc_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(acc_, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 280, 161, 41));

        hospital_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospital_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hospital_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 320, 282, 41));

        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 361, 282, 41));
        getContentPane().add(state1_, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 222, 161, 42));
        getContentPane().add(state2_, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 222, 282, 42));
        getContentPane().add(state3_, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 222, 160, 42));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("step 1    :    The first step you've already done. Creating an account... ");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 474, 360, 30));

        jLabel3.setText(" step 2   :    Second step,  Order through the software to get vaccine from your desired hospital...");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 610, 30));

        jLabel4.setText(" before the hospital accepts your request you'll be in PENDING mode. After aproval you'll see Approved. ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 550, 660, 20));

        jLabel5.setText("step 3    :   after everything is done you'll be able to generate slip and all good to go");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 590, 680, -1));

        jLabel6.setText("thank you, ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 640, 80, -1));

        drag_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main panel.png"))); // NOI18N
        drag_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drag_MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drag_MouseMoved(evt);
            }
        });
        drag_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drag_MousePressed(evt);
            }
        });
        getContentPane().add(drag_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1066, 799));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reqVaccine_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reqVaccine_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccine hover.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req hover.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_reqVaccine_MouseMoved

    private void reqVaccine_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reqVaccine_MouseClicked
        // TODO add your handling code here:
        
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();

        customerPage cp = new customerPage(nx,ny,customer_id);
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reqVaccine_MouseClicked

    private void track_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_track_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccing.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req hover.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_track_MouseMoved

    private void track_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_track_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_track_MouseClicked

    private void logout_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_MouseMoved
        // TODO add your handling code here:
        ImageIcon logout = new ImageIcon(getClass().getResource("logoutHOver.png"));
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("report.png"));
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("app.png"));
        getApp_.setIcon(gapp);
    }//GEN-LAST:event_logout_MouseMoved

    private void logout_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_MouseClicked
        // TODO add your handling code here:
        this.dispose();
        accessibility ac = new accessibility();
        ac.setVisible(true);
    }//GEN-LAST:event_logout_MouseClicked

    private void report_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_MouseMoved
        // TODO add your handling code here:
        ImageIcon logout = new ImageIcon(getClass().getResource("logout.png"));
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("reportHover.png"));
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("app.png"));
        getApp_.setIcon(gapp);
    }//GEN-LAST:event_report_MouseMoved

    private void report_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_report_MouseClicked

    private void getApp_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getApp_MouseMoved
        // TODO add your handling code here:
        ImageIcon logout = new ImageIcon(getClass().getResource("logout.png"));
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("report.png"));
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("appHover.png"));
        getApp_.setIcon(gapp);
    }//GEN-LAST:event_getApp_MouseMoved

    private void getApp_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getApp_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_getApp_MouseClicked

    private void drag_MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_drag_MouseDragged

    private void drag_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccing.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req hover.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);

        ImageIcon logout = new ImageIcon(getClass().getResource("logout.png"));
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("report.png"));
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("app.png"));
        getApp_.setIcon(gapp);
    }//GEN-LAST:event_drag_MouseMoved

    private void drag_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_drag_MousePressed

    private void slip_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slip_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccing.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req hover.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen hover.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_slip_MouseMoved

    private void slip_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slip_MouseClicked
        // TODO add your handling code here:
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();

        slip slip = new slip(nx,ny,customer_id);
        slip.setVisible(true);
    }//GEN-LAST:event_slip_MouseClicked

    private void appointment_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointment_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccing.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req hover.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointmenthover.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_appointment_MouseMoved

    private void appointment_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointment_MouseClicked
        // TODO add your handling code here:

        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();

        customerAppointment ca = new customerAppointment(nx,ny,customer_id);
        ca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appointment_MouseClicked

    private void payemnt_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payemnt_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccing.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req hover.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment hover.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_payemnt_MouseMoved

    private void payemnt_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payemnt_MouseClicked
        // TODO add your handling code here:

        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();

        customerPayment cp = new customerPayment(nx,ny,customer_id);
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_payemnt_MouseClicked

    private void effects_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_effects_MouseMoved
        // TODO add your handling code here:
        ImageIcon req = new ImageIcon(getClass().getResource("request vaccing.png"));
        reqVaccine_.setIcon(req);
        ImageIcon tr = new ImageIcon(getClass().getResource("track req hover.png"));
        track_.setIcon(tr);
        ImageIcon ap = new ImageIcon(getClass().getResource("appointment.png"));
        appointment_.setIcon(ap);
        ImageIcon pay = new ImageIcon(getClass().getResource("payment.png"));
        payemnt_.setIcon(pay);
        ImageIcon eff = new ImageIcon(getClass().getResource("sideeffects hover.png"));
        effects_.setIcon(eff);
        ImageIcon slip = new ImageIcon(getClass().getResource("slip gen.png"));
        slip_.setIcon(slip);
    }//GEN-LAST:event_effects_MouseMoved

    private void effects_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_effects_MouseClicked
        // TODO add your handling code here:
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();

        customerSideEffects cse = new customerSideEffects(nx,ny,customer_id);
        cse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_effects_MouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();

        customerProfile cp = new customerProfile (nx,ny,customer_id);
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerTrackReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerTrackReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerTrackReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerTrackReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerTrackReq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_;
    private javax.swing.JLabel appointment_;
    private javax.swing.JLabel completed_;
    private javax.swing.JLabel drag_;
    private javax.swing.JLabel effects_;
    private javax.swing.JLabel getApp_;
    private javax.swing.JLabel hospital_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel logout_;
    private javax.swing.JLabel payemnt_;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel report_;
    private javax.swing.JLabel reqVaccine_;
    private javax.swing.JLabel slip_;
    private javax.swing.JLabel state1_;
    private javax.swing.JLabel state2_;
    private javax.swing.JLabel state3_;
    private javax.swing.JLabel status;
    private javax.swing.JLabel track_;
    // End of variables declaration//GEN-END:variables
}
