
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class doctorPage extends javax.swing.JFrame {

    //mouse drag
        int mouseX;
        int mouseY;
        // screen pos
        int wid = (Toolkit.getDefaultToolkit().getScreenSize().width)/2-533;
        int hit = (Toolkit.getDefaultToolkit().getScreenSize().height)/2-400;

        int X;
        int Y;
        
        String docID = "";
        
    public doctorPage(int x, int y, String doctorID) {
        initComponents();
        
        //icon image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
        // position
        this.setLocation(x,y);
        
        System.out.println(doctorID);
        docID = doctorID;
    }
    
    public doctorPage() {
        initComponents();
        
        //icon image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
        // position
        this.setLocation(wid,hit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profile = new javax.swing.JLabel();
        requests_ = new javax.swing.JLabel();
        adHour_ = new javax.swing.JLabel();
        appointments_ = new javax.swing.JLabel();
        logout_ = new javax.swing.JLabel();
        report_ = new javax.swing.JLabel();
        getApp_ = new javax.swing.JLabel();
        drag_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 28, 37, 37));

        requests_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/requestsHover.png"))); // NOI18N
        requests_.setText("jLabel2");
        requests_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        requests_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                requests_MouseMoved(evt);
            }
        });
        requests_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requests_MouseClicked(evt);
            }
        });
        getContentPane().add(requests_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 195, 60));

        adHour_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/advising.png"))); // NOI18N
        adHour_.setText("jLabel2");
        adHour_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adHour_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                adHour_MouseMoved(evt);
            }
        });
        adHour_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adHour_MouseClicked(evt);
            }
        });
        getContentPane().add(adHour_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, 195, 60));

        appointments_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appointment.png"))); // NOI18N
        appointments_.setText("jLabel2");
        appointments_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appointments_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                appointments_MouseMoved(evt);
            }
        });
        appointments_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointments_MouseClicked(evt);
            }
        });
        getContentPane().add(appointments_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, 195, 60));

        logout_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logout_.setText("jLabel2");
        logout_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logout_MouseMoved(evt);
            }
        });
        logout_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_MouseClicked(evt);
            }
        });
        getContentPane().add(logout_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 609, 195, 60));

        report_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        report_.setText("jLabel2");
        report_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        report_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                report_MouseMoved(evt);
            }
        });
        report_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                report_MouseClicked(evt);
            }
        });
        getContentPane().add(report_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 669, 195, 60));

        getApp_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.png"))); // NOI18N
        getApp_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getApp_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                getApp_MouseMoved(evt);
            }
        });
        getApp_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getApp_MouseClicked(evt);
            }
        });
        getContentPane().add(getApp_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 729, 195, 60));

        drag_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main panel.png"))); // NOI18N
        drag_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drag_MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drag_MouseMoved(evt);
            }
        });
        drag_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drag_MousePressed(evt);
            }
        });
        getContentPane().add(drag_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1066, 799));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_MouseClicked
        // TODO add your handling code here:
        this.dispose();
        accessibility ac = new accessibility();
        ac.setVisible(true);
    }//GEN-LAST:event_logout_MouseClicked

    private void drag_MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_drag_MouseDragged

    private void drag_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_drag_MousePressed

    private void requests_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requests_MouseMoved
        // TODO add your handling code here:
        
        ImageIcon dreq = new ImageIcon(getClass().getResource("requestsHover.png")); 
        requests_.setIcon(dreq);
        ImageIcon adv = new ImageIcon(getClass().getResource("advising.png")); 
        adHour_.setIcon(adv);
        ImageIcon appoint = new ImageIcon(getClass().getResource("appointment.png")); 
        appointments_.setIcon(appoint);
        
    }//GEN-LAST:event_requests_MouseMoved

    private void drag_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MouseMoved
        // TODO add your handling code here:
        ImageIcon dreq = new ImageIcon(getClass().getResource("requestsHover.png")); 
        requests_.setIcon(dreq);
        ImageIcon adv = new ImageIcon(getClass().getResource("advising.png")); 
        adHour_.setIcon(adv);
        ImageIcon appoint = new ImageIcon(getClass().getResource("appointment.png")); 
        appointments_.setIcon(appoint);
        
        ImageIcon logout = new ImageIcon(getClass().getResource("logout.png")); 
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("report.png")); 
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("app.png")); 
        getApp_.setIcon(gapp);
        
    }//GEN-LAST:event_drag_MouseMoved

    private void adHour_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adHour_MouseClicked
        // TODO add your handling code here:
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();
        
        doctorAdvising da = new doctorAdvising (nx,ny,docID);
        da.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_adHour_MouseClicked

    private void adHour_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adHour_MouseMoved
        // TODO add your handling code here:
        ImageIcon adv = new ImageIcon(getClass().getResource("advisingHover.png")); 
        adHour_.setIcon(adv);
        ImageIcon dreq = new ImageIcon(getClass().getResource("requestsHover.png")); 
        requests_.setIcon(dreq);
        ImageIcon appoint = new ImageIcon(getClass().getResource("appointment.png")); 
        appointments_.setIcon(appoint);
    }//GEN-LAST:event_adHour_MouseMoved

    private void appointments_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointments_MouseClicked
        // TODO add your handling code here:
        
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();
        
        doctorAppointment dap = new doctorAppointment (nx,ny,docID);
        dap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appointments_MouseClicked

    private void appointments_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointments_MouseMoved
        // TODO add your handling code here:
        ImageIcon appoint = new ImageIcon(getClass().getResource("appointmentHover.png")); 
        appointments_.setIcon(appoint);
        ImageIcon dreq = new ImageIcon(getClass().getResource("requestsHover.png")); 
        requests_.setIcon(dreq);
        ImageIcon adv = new ImageIcon(getClass().getResource("advising.png")); 
        adHour_.setIcon(adv);
    }//GEN-LAST:event_appointments_MouseMoved

    private void logout_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_MouseMoved
        // TODO add your handling code here:
        ImageIcon logout = new ImageIcon(getClass().getResource("logoutHOver.png")); 
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("report.png")); 
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("app.png")); 
        getApp_.setIcon(gapp);
    }//GEN-LAST:event_logout_MouseMoved

    private void report_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_report_MouseClicked

    private void report_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_report_MouseMoved
        // TODO add your handling code here:
        ImageIcon logout = new ImageIcon(getClass().getResource("logout.png")); 
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("reportHover.png")); 
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("app.png")); 
        getApp_.setIcon(gapp);
        
    }//GEN-LAST:event_report_MouseMoved

    private void getApp_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getApp_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_getApp_MouseClicked

    private void getApp_MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getApp_MouseMoved
        // TODO add your handling code here:
        ImageIcon logout = new ImageIcon(getClass().getResource("logout.png")); 
        logout_.setIcon(logout);
        ImageIcon askQ = new ImageIcon(getClass().getResource("report.png")); 
        report_.setIcon(askQ);
        ImageIcon gapp = new ImageIcon(getClass().getResource("appHover.png")); 
        getApp_.setIcon(gapp);
    }//GEN-LAST:event_getApp_MouseMoved

    private void requests_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requests_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_requests_MouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
        int nx = (int) getLocation().getX();
        int ny = (int) getLocation().getY();

        doctorProfile cp = new doctorProfile (nx,ny,docID);
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adHour_;
    private javax.swing.JLabel appointments_;
    private javax.swing.JLabel drag_;
    private javax.swing.JLabel getApp_;
    private javax.swing.JLabel logout_;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel report_;
    private javax.swing.JLabel requests_;
    // End of variables declaration//GEN-END:variables
}
