
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class signUP extends javax.swing.JFrame {

        //mouse drag
        int mouseX;
        int mouseY;
        // screen pos
        int wid = (Toolkit.getDefaultToolkit().getScreenSize().width)/2-170;
        int hit = (Toolkit.getDefaultToolkit().getScreenSize().height)/2-422;

        int X;
        int Y;
            
    
    
    public signUP(int x, int y) {
        initComponents();
        
        // position
        this.setLocation(wid,hit);
        
        //icon image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
        //opaque error
        name_.setBackground(new java.awt.Color(255,255,255,0));
        userName_.setBackground(new java.awt.Color(255,255,255,0));
        phone_.setBackground(new java.awt.Color(255,255,255,0));
        DOB_.setBackground(new java.awt.Color(255,255,255,0));
        NID_.setBackground(new java.awt.Color(255,255,255,0));
        address_.setBackground(new java.awt.Color(255,255,255,0));
        pass_.setBackground(new java.awt.Color(255,255,255,0));
        conpass_.setBackground(new java.awt.Color(255,255,255,0));
        
        // back pos
        X=x;
        Y=y;
       
    }

    
    public signUP() {
        initComponents();
        
        //icon image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
        //opaque error
        name_.setBackground(new java.awt.Color(255,255,255,0));
        userName_.setBackground(new java.awt.Color(255,255,255,0));
        phone_.setBackground(new java.awt.Color(255,255,255,0));
        DOB_.setBackground(new java.awt.Color(255,255,255,0));
        NID_.setBackground(new java.awt.Color(255,255,255,0));
        address_.setBackground(new java.awt.Color(255,255,255,0));
        pass_.setBackground(new java.awt.Color(255,255,255,0));
        conpass_.setBackground(new java.awt.Color(255,255,255,0));
        
        // position
        this.setLocation(wid,hit);
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        name_ = new javax.swing.JTextField();
        userName_ = new javax.swing.JTextField();
        mail_ = new javax.swing.JTextField();
        phone_ = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        DOB_ = new javax.swing.JTextField();
        NID_ = new javax.swing.JTextField();
        address_ = new javax.swing.JTextField();
        pass_ = new javax.swing.JPasswordField();
        conpass_ = new javax.swing.JPasswordField();
        quit_ = new javax.swing.JLabel();
        signUPcustomer = new javax.swing.JLabel();
        signUP_ = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        drag_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_.setText("Name");
        name_.setToolTipText("do not use the email in the demo");
        name_.setBorder(null);
        name_.setOpaque(false);
        name_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                name_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                name_MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                name_MouseReleased(evt);
            }
        });
        name_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_ActionPerformed(evt);
            }
        });
        getContentPane().add(name_, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 173, 250, 20));

        userName_.setText("Username");
        userName_.setToolTipText("do not use the email in the demo");
        userName_.setBorder(null);
        userName_.setOpaque(false);
        userName_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userName_MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userName_MouseReleased(evt);
            }
        });
        getContentPane().add(userName_, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 226, 250, 20));

        mail_.setText("E-mail");
        mail_.setToolTipText("do not use the email in the demo");
        mail_.setBorder(null);
        mail_.setOpaque(false);
        mail_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mail_MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mail_MouseReleased(evt);
            }
        });
        getContentPane().add(mail_, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 337, 250, 20));

        phone_.setText("Phone");
        phone_.setToolTipText("do not use the email in the demo");
        phone_.setBorder(null);
        phone_.setOpaque(false);
        phone_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phone_MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                phone_MouseReleased(evt);
            }
        });
        getContentPane().add(phone_, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 282, 250, 20));

        female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(female);
        female.setText("female");
        female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male);
        male.setText("male");
        male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        DOB_.setText("Date of Birth (dd-mm-yyyy)");
        DOB_.setToolTipText("do not use the email in the demo");
        DOB_.setBorder(null);
        DOB_.setOpaque(false);
        DOB_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DOB_MouseReleased(evt);
            }
        });
        getContentPane().add(DOB_, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 250, 20));

        NID_.setText("NID no");
        NID_.setToolTipText("do not use the email in the demo");
        NID_.setBorder(null);
        NID_.setOpaque(false);
        NID_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NID_MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NID_MouseReleased(evt);
            }
        });
        getContentPane().add(NID_, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 505, 250, 20));

        address_.setText("Address");
        address_.setToolTipText("do not use the email in the demo");
        address_.setBorder(null);
        address_.setOpaque(false);
        address_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                address_MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                address_MouseReleased(evt);
            }
        });
        getContentPane().add(address_, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 667, 250, 20));

        pass_.setText("password");
        pass_.setBorder(null);
        pass_.setOpaque(false);
        pass_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass_MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pass_MouseReleased(evt);
            }
        });
        getContentPane().add(pass_, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 557, 230, 20));

        conpass_.setText("password");
        conpass_.setBorder(null);
        conpass_.setOpaque(false);
        conpass_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conpass_MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                conpass_MouseReleased(evt);
            }
        });
        getContentPane().add(conpass_, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 614, 230, 20));

        quit_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x30.png"))); // NOI18N
        quit_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quit_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quit_MouseClicked(evt);
            }
        });
        getContentPane().add(quit_, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 30, 30));

        signUPcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup button.png"))); // NOI18N
        signUPcustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUPcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUPcustomerMouseClicked(evt);
            }
        });
        getContentPane().add(signUPcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 736, 82, 30));

        signUP_.setForeground(new java.awt.Color(0, 153, 255));
        signUP_.setText("login");
        signUP_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUP_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUP_MouseClicked(evt);
            }
        });
        getContentPane().add(signUP_, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 788, -1, -1));

        jLabel2.setText("already have an account?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 788, -1, -1));

        drag_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signUP.png"))); // NOI18N
        drag_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drag_MouseDragged(evt);
            }
        });
        drag_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drag_MousePressed(evt);
            }
        });
        getContentPane().add(drag_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 844));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drag_MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_drag_MouseDragged

    private void drag_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_drag_MousePressed

    private void name_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_MouseReleased
        // clears box if its hint mail
        if (name_.getText().equals("email@gmail.com")){
            name_.setText("");
        }
    }//GEN-LAST:event_name_MouseReleased

    private void NID_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NID_MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_NID_MouseReleased

    private void DOB_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOB_MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_DOB_MouseReleased

    private void phone_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phone_MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_MouseReleased

    private void address_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_address_MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_address_MouseReleased

    private void userName_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userName_MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_userName_MouseReleased

    private void name_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_ActionPerformed

    private void pass_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass_MouseReleased
        // gets the value of password to string type as pass_ is in char
        String pass = String.valueOf(pass_.getPassword());
        // compares if its demo pass or not then makes it invisible
        if (pass.equals("password")){
            pass_.setText("");
        }
    }//GEN-LAST:event_pass_MouseReleased

    private void conpass_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conpass_MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_conpass_MouseReleased

    private void signUPcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUPcustomerMouseClicked
        // TODO add your handling code here:
        String gender = "";
         try {
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection("jdbc:sqlserver://localhost:1433;databaseName=SD3104;selectMethod=cursor", "sa", "123456");
            
            
            //generate id
            String cid = "SELECT COUNT(*) AS customercount FROM customer";
            PreparedStatement pstid =  connection.prepareStatement (cid);
            ResultSet rsid = pstid.executeQuery();
            int idpre=0;
            
            if (rsid.next()){
            idpre = rsid.getInt("customercount");
            }
            idpre+=1;
            String idpr = Integer.toString(idpre);
            String idFinal = "CVDC"+idpr;
            
           
            
            
            
            String p= "insert into customer (customer_id, customer_name, customer_adress, customer_phn_no, date_of_birth, gender, NID, customer_mail, customer_username, customer_pass) values (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst =  connection.prepareStatement (p);
            
            pst.setString(1, idFinal);
            pst.setString(2, name_.getText());
            pst.setString(3, address_.getText());
            pst.setString(4, phone_.getText());
            //SimpleDateFormat formt = new SimpleDateFormat("dd-MM-yyyy");
            //String DOB = formt.format(DOB_.getDate());
            //pst.setString(6, DOB);
            pst.setString(5, "01-01-1999");
            
            if (male.isSelected()){
                gender = "male";
            }
            if (female.isSelected()){
                gender = "female";
            }
            pst.setString(6, gender);
            
            
            pst.setString(7, NID_.getText());
            pst.setString(8, mail_.getText());
            
            pst.setString(9, userName_.getText());
            
            String pass = String.valueOf(pass_.getPassword());
            pst.setString(10, pass);
            
            
            pst.executeUpdate();
            login lp = new login();
            lp.setVisible(true);
            this.dispose();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
         
        
        
        
        
        
    }//GEN-LAST:event_signUPcustomerMouseClicked

    private void quit_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quit_MouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_quit_MouseClicked

    private void signUP_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUP_MouseClicked
        // TODO add your handling code here:
        this.dispose();
        login log = new login(X,Y);
        log.setVisible(true);
    }//GEN-LAST:event_signUP_MouseClicked

    private void name_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_name_MouseEntered

    private void name_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_MouseClicked
        // TODO add your handling code here:
        String name = String.valueOf(name_.getText());
        if (name.equals("Name")){
            name_.setText("");
        }
    }//GEN-LAST:event_name_MouseClicked

    private void userName_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userName_MouseClicked
        // TODO add your handling code here:
        String username = String.valueOf(userName_.getText());
        if (username.equals("Username")){
            userName_.setText("");
        }
    }//GEN-LAST:event_userName_MouseClicked

    private void phone_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phone_MouseClicked
        // TODO add your handling code here:
        String phone = String.valueOf(phone_.getText());
        if (phone.equals("Phone")){
            phone_.setText("");
        }
    }//GEN-LAST:event_phone_MouseClicked

    private void NID_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NID_MouseClicked
        // TODO add your handling code here:
        String nid = String.valueOf(NID_.getText());
        if (nid.equals("NID no")){
            NID_.setText("");
        }
    }//GEN-LAST:event_NID_MouseClicked

    private void conpass_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conpass_MouseClicked
        String pass = String.valueOf(pass_.getPassword());
        // compares if its demo pass or not then makes it invisible
        if (pass.equals("password")){
            conpass_.setText("");
        }        
    }//GEN-LAST:event_conpass_MouseClicked

    private void pass_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_MouseClicked

    private void address_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_address_MouseClicked
        // TODO add your handling code here:
        String address = String.valueOf(address_.getText());
        if (address.equals("Address")){
            address_.setText("");
        }
    }//GEN-LAST:event_address_MouseClicked

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void mail_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mail_MouseClicked
        String mail = String.valueOf(mail_.getText());
        if (mail.equals("E-mail")){
            mail_.setText("");
        }
                
    }//GEN-LAST:event_mail_MouseClicked

    private void mail_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mail_MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mail_MouseReleased

    
    
    
    public boolean verifyEmptyMismatch(){
    
            String name = name_.getText();
            String userName = userName_.getText();
            String pass = String.valueOf(pass_.getPassword());
            String conPass = String.valueOf(conpass_.getPassword());
            //String email = mail_.getText();
            
            // one field empty
            //if (name.trim().equals("") || userName.trim().equals("") || email.trim().equals("") ||
            //        pass.equals("") || conPass.equals("")){
            
            //    popLogEmpty pop1 = new popLogEmpty ();
            //    pop1.setVisible(true);
                return false;
            //}
            
                // password mismatch
                //else if (!pass.equals(conPass)){
                
                //    popMismatch pop2 = new popMismatch();
                //    pop2.setVisible(true);         
                //    return false;
                //}
                
                // invalid mail
                //else if (!validMail(email)) {
                       
                //        popInvalidMail pop6 = new popInvalidMail();
                //        pop6.setVisible(true); 
                //        return false;
                //    }
                            
            //else return true;
    
    }
    
    
    public boolean validMail(String mail){
        
        String emailregx = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$";
        Pattern emailPat = Pattern.compile(emailregx,Pattern.CASE_INSENSITIVE);
        Matcher matcher = emailPat.matcher(mail);
        
        return matcher.find();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOB_;
    private javax.swing.JTextField NID_;
    private javax.swing.JTextField address_;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField conpass_;
    private javax.swing.JLabel drag_;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField mail_;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name_;
    private javax.swing.JPasswordField pass_;
    private javax.swing.JTextField phone_;
    private javax.swing.JLabel quit_;
    private javax.swing.JLabel signUP_;
    private javax.swing.JLabel signUPcustomer;
    private javax.swing.JTextField userName_;
    // End of variables declaration//GEN-END:variables
}
