
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class slip extends javax.swing.JFrame {

     //mouse drag
    int mouseX;
    int mouseY;
    // screen pos
    int wid = (Toolkit.getDefaultToolkit().getScreenSize().width)/2-350;
    int hit = (Toolkit.getDefaultToolkit().getScreenSize().height)/2-300;
    
    String customer_id = "";
    
    
    public slip(int x, int y, String customerID) {
        initComponents();
        
        //icon image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
        // position
        this.setLocation(wid,hit);
        
        customer_id=customerID;
        
        try {
                                          
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
Connection connection = DriverManager
.getConnection(
"jdbc:sqlserver://localhost:1433;databaseName=SD3104;selectMethod=cursor", "sa", "123456");
System.out.println("DATABASE NAME IS:"
+ connection.getMetaData().getDatabaseProductName());
Statement statement = connection.createStatement();
ResultSet resultSet = statement
.executeQuery(" select customer.customer_name ,accounts.vaccine_id,vaccine.manufacture_name,accounts.sale+(accounts.vat*0.01*accounts.sale) as price,accounts.dose_info,dateadd(dd,21,dose_info) as nextDate"
        + " from customer inner join accounts on customer.customer_id=accounts.customer_id inner join vaccine on accounts.vaccine_id=vaccine.vaccine_id"
        + "  where accounts.customer_id='"+customer_id+"'");

resultSet.next();
String firstDate=resultSet.getString("dose_info");
String cusName  =resultSet.getString("customer_name");
String vacId  =resultSet.getString("vaccine_id");
String manName  =resultSet.getString("manufacture_name");
String price  =resultSet.getString("price");
String nextDate= resultSet.getString("nextDate");

            System.out.println(firstDate+cusName+vacId+manName+price); 

ResultSet rst=statement.executeQuery("select hospital_name from accounts inner join hospital on hospital.hospital_id=accounts.hospital_id where customer_id='"+customer_id+"'");
rst.next();
            
            System.out.println(rst.getString("hospital_name"));
            name_.setText(cusName);
            hosname_.setText(rst.getString("hospital_name"));
            manuf_.setText(manName);
            date_.setText(firstDate);
            vaccineid_.setText(vacId);
            paid_.setText(price);
            nextDate_.setText(nextDate);
            nexthos_.setText(rst.getString("hospital_name"));
            vaccine2id_.setText(vacId);
            manuf2_.setText(manName);

} catch (Exception e) {
e.printStackTrace();
}
        
        
        
        
        
        
        
        
        
        
        
    }
    
    public slip() {
        initComponents();
        
        //icon image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
        // position
        this.setLocation(wid,hit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hosname_ = new javax.swing.JLabel();
        print_ = new javax.swing.JLabel();
        quit_ = new javax.swing.JLabel();
        manuf_ = new javax.swing.JLabel();
        date_ = new javax.swing.JLabel();
        vaccineid_ = new javax.swing.JLabel();
        name_ = new javax.swing.JLabel();
        paid_ = new javax.swing.JLabel();
        nextDate_ = new javax.swing.JLabel();
        nexthos_ = new javax.swing.JLabel();
        vaccine2id_ = new javax.swing.JLabel();
        manuf2_ = new javax.swing.JLabel();
        drag_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hosname_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hosname_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(hosname_, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 297, 170, 50));

        print_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_MouseClicked(evt);
            }
        });
        jPanel1.add(print_, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 450, 28, 28));

        quit_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x30w.png"))); // NOI18N
        quit_.setToolTipText("Exit");
        quit_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quit_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quit_MouseClicked(evt);
            }
        });
        jPanel1.add(quit_, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 30, 30));
        jPanel1.add(manuf_, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 200, 19));
        jPanel1.add(date_, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 312, 66, 19));
        jPanel1.add(vaccineid_, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 200, 19));
        jPanel1.add(name_, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 160, 130, 19));

        paid_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paid_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(paid_, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 210, 30));
        jPanel1.add(nextDate_, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 384, 66, 19));

        nexthos_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nexthos_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(nexthos_, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 372, 170, 50));
        jPanel1.add(vaccine2id_, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 374, 200, 20));
        jPanel1.add(manuf2_, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 404, 200, 20));

        drag_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slip.png"))); // NOI18N
        drag_.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drag_MouseDragged(evt);
            }
        });
        drag_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drag_MousePressed(evt);
            }
        });
        jPanel1.add(drag_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 775, 581));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 775, 581));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quit_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quit_MouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_quit_MouseClicked

    private void drag_MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_drag_MouseDragged

    private void drag_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drag_MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_drag_MousePressed

    private void print_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_MouseClicked
        // TODO add your handling code here:
        
        PrinterJob pjob = PrinterJob.getPrinterJob();
        pjob.setPrintable(new Printable(){
         public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum>0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(.79,.79);
                
                jPanel1.print(g2);          
                return Printable.PAGE_EXISTS;
                         
                
            }
        
        });
        boolean ok = pjob.printDialog();
        if(ok){
        try{
            
        pjob.print();
        }
        catch (PrinterException ex){}
        }
        
        /*slip sl = new slip();
        PrinterJob pjob = PrinterJob.getPrinterJob();
        PageFormat preformat = pjob.defaultPage();
        preformat.setOrientation(PageFormat.LANDSCAPE);
        PageFormat postformat = pjob.pageDialog(preformat);
        
        //If user does not hit cancel then print.
        if (preformat != postformat) {
            //Set print component
            pjob.setPrintable(new Printer(sl), postformat);
            if (pjob.printDialog()) {
                try {
                    pjob.print();
                } catch (PrinterException ex) {
                    Logger.getLogger(slip.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }*/


    }//GEN-LAST:event_print_MouseClicked


    
    public static class Printer implements Printable {
    final Component comp;

    public Printer(Component comp){
        this.comp = comp;
    }

    @Override
    public int print(Graphics g, PageFormat format, int page_index) 
            throws PrinterException {
        if (page_index > 0) {
            return Printable.NO_SUCH_PAGE;
        }

        // get the bounds of the component
        Dimension dim = comp.getSize();
        double cHeight = dim.getHeight();
        double cWidth = dim.getWidth();

        // get the bounds of the printable area
        double pHeight = format.getImageableHeight();
        double pWidth = format.getImageableWidth();
        System.out.println(pHeight);
        System.out.println(pWidth);

        double pXStart = format.getImageableX();
        double pYStart = format.getImageableY();
        System.out.println(pXStart);
        System.out.println(pYStart);

        double xRatio = pWidth / cWidth;
        double yRatio = pHeight / cHeight;


        Graphics2D g2 = (Graphics2D) g;
        g2.translate(pXStart, pYStart);
        g2.scale(xRatio, yRatio);
        comp.printAll(g2);

        return Printable.PAGE_EXISTS;
    }
}
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new slip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_;
    private javax.swing.JLabel drag_;
    private javax.swing.JLabel hosname_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manuf2_;
    private javax.swing.JLabel manuf_;
    private javax.swing.JLabel name_;
    private javax.swing.JLabel nextDate_;
    private javax.swing.JLabel nexthos_;
    private javax.swing.JLabel paid_;
    private javax.swing.JLabel print_;
    private javax.swing.JLabel quit_;
    private javax.swing.JLabel vaccine2id_;
    private javax.swing.JLabel vaccineid_;
    // End of variables declaration//GEN-END:variables
}
